export const OPEN_UPDATE_EDITOR = "OPEN_UPDATE_EDITOR";
export const HANDLE_ON_PASTE = "HANDLE_ON_PASTE";
export const EDITOR_TITLE_CHANGE = "EDITOR_TITLE_CHANGE";
export const EDITOR_CHANGE = "EDITOR_CHANGE";
export const UPDATE_POSITION = "UPDATE_POSITION";

export const ADD_EDITOR_WITH_POSITION = "ADD_EDITOR_WITH_POSITION";
export const ADD_EDITOR = "ADD_EDITOR";

export const REMOVE_EDITOR = "REMOVE_EDITOR";
export const REMOVE_EDITOR_TOOLBAR = "REMOVE_EDITOR_TOOLBAR";
export const REMOVE_EDITOR_REACT_ELEMENT = "REMOVE_EDITOR_REACT_ELEMENT";

export const EXTRACT_DATA = "EXTRACT_DATA";

export const MOVE_EDITOR_UP = "MOVE_EDITOR_UP";
export const MOVE_EDITOR_UP_REACT_ELEMENT = "MOVE_EDITOR_UP_REACT_ELEMENT";
export const MOVE_EDITOR_DOWN = "MOVE_EDITOR_DOWN";
export const MOVE_EDITOR_DOWN_REACT_ELEMENT = "MOVE_EDITOR_DOWN_REACT_ELEMENT";

export const HANDLE_KEYUP = "HANDLE_KEYUP";
